name: foodhero_app
description: A new Flutter project.

publish_to: "none"

version: 1.1.24+54

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  awesome_notifications: ^0.6.21
  bloc: ^8.1.0
  cached_network_image: ^3.2.3
  carousel_slider: ^4.1.1
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  elegant_notification: ^1.6.4
  firebase_analytics: ^10.0.5
  firebase_auth: ^4.1.2
  firebase_core: ^2.2.0
  firebase_messaging: ^14.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_dotenv: ^5.0.2
  flutter_launcher_icons: ^0.10.0
  flutter_local_notifications: ^12.0.3
  flutter_map: ^3.0.0
  flutter_map_marker_cluster: ^1.0.1
  flutter_native_timezone: ^2.0.0
  flutter_rating_bar: ^4.0.1
  flutter_secure_storage: ^6.1.0
  flutter_svg: ^1.1.6
  font_awesome_flutter: ^10.2.1
  geocoding: ^2.0.5
  geolocator: ^9.0.2
  get: ^4.6.5
  google_fonts: ^3.0.1
  google_sign_in: ^5.4.2
  http: ^0.13.5
  intl: ^0.17.0
  localstore: ^1.2.3
  lottie: ^2.0.0
  mask: ^1.0.4
  new_version_plus: ^0.0.4
  pinput: ^2.2.16
  provider: ^6.0.4
  rxdart: ^0.27.6
  shared_preferences: ^2.0.15
  sign_in_with_apple: ^4.2.0
  sqflite: ^2.2.0+3
  timezone: ^0.9.0
  url_launcher: ^6.1.6

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/IconFoodHero.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/icons/
    - assets/images/

